"""Messaging constants."""

SENDER_ROLE_CREATOR = "CREATOR"
SENDER_ROLE_FAN = "FAN"

MESSAGE_TYPE_TEXT = "TEXT"
MESSAGE_TYPE_MEDIA = "MEDIA"
MESSAGE_TYPE_SYSTEM = "SYSTEM"

DEFAULT_PAGE_SIZE = 50
MAX_PAGE_SIZE = 100
