export type ComparisonData = {
  name: string;
  slug: string;
  title: string;
  description: string;
  summary: string;
  features: { feature: string; zinovia: string; competitor: string }[];
  fees: { label: string; zinovia: string; competitor: string }[];
  payoutSpeed: { zinovia: string; competitor: string };
  bestFor: { zinovia: string; competitor: string };
  faqs: { q: string; a: string }[];
};

export const COMPARISONS: Record<string, ComparisonData> = {
  patreon: {
    name: "Patreon",
    slug: "patreon",
    title: "Zinovia vs Patreon: Fees, Features & Payouts (2026)",
    description: "Compare Zinovia vs Patreon: fees, payout speed, features, and creator tools side by side. See why creators are switching.",
    summary: "Zinovia offers faster payouts (48 hours vs 30+ days), lower platform fees, built-in private messaging, and signed-URL content security — features Patreon charges extra for or doesn't offer.",
    features: [
      { feature: "Monthly Subscriptions", zinovia: "Yes", competitor: "Yes" },
      { feature: "Pay-Per-View Content", zinovia: "Yes", competitor: "Limited" },
      { feature: "Direct Messaging", zinovia: "Built-in", competitor: "Add-on" },
      { feature: "Content Encryption", zinovia: "Signed URLs + AES", competitor: "Basic" },
      { feature: "Creator Verification (KYC)", zinovia: "Yes", competitor: "No" },
      { feature: "Fan Tips", zinovia: "Yes", competitor: "Yes" },
      { feature: "Analytics Dashboard", zinovia: "Yes", competitor: "Yes" },
      { feature: "Multi-Language Platform", zinovia: "9 languages", competitor: "English primary" },
      { feature: "Age Verification", zinovia: "Built-in", competitor: "No" },
      { feature: "Custom Creator Profiles", zinovia: "Yes", competitor: "Yes" },
    ],
    fees: [
      { label: "Platform Fee", zinovia: "Competitive", competitor: "5-12%" },
      { label: "Payment Processing", zinovia: "Standard processing fee", competitor: "Included in platform fee" },
      { label: "Monthly Fee", zinovia: "None", competitor: "None" },
      { label: "Payout Fee", zinovia: "None", competitor: "Varies by method" },
    ],
    payoutSpeed: { zinovia: "48 hours", competitor: "30+ days" },
    bestFor: {
      zinovia: "Creators who want fast payouts, private content delivery, multilingual reach, and built-in messaging.",
      competitor: "Creators with established audiences who primarily use English and don't need fast payouts.",
    },
    faqs: [
      { q: "Is Zinovia a good alternative to Patreon?", a: "Yes. Zinovia offers faster payouts (48 hours vs 30+ days), built-in private messaging, content encryption with signed URLs, and support for 9 languages — all with competitive fees." },
      { q: "Can I migrate from Patreon to Zinovia?", a: "Yes. Create your Zinovia account, set up your profile and subscription tiers, then redirect your audience to your new page. Your content and subscriber relationships transfer with you." },
      { q: "How do Zinovia's fees compare to Patreon?", a: "Zinovia charges a competitive platform fee with no hidden charges. Patreon charges 5-12% depending on your plan, plus payment processing fees on some tiers." },
      { q: "Does Zinovia support the same content types as Patreon?", a: "Yes. Zinovia supports text posts, images, videos, paid unlocks, subscriptions, tips, and direct messaging — plus additional features like content encryption and age verification." },
      { q: "Which platform has better payout speed?", a: "Zinovia pays creators within 48 hours via secure bank transfer. Patreon processes payouts monthly, typically taking 30+ days from when a patron is charged." },
    ],
  },
  onlyfans: {
    name: "OnlyFans",
    slug: "onlyfans",
    title: "Zinovia vs OnlyFans: Which Platform Is Better for Creators?",
    description: "Compare Zinovia vs OnlyFans: fees, features, content security, and payouts. Find the right creator platform for your needs.",
    summary: "Zinovia provides better content security (signed URLs), faster payouts (48 hours), multilingual support (9 languages), and creator verification — while OnlyFans has a larger existing user base.",
    features: [
      { feature: "Monthly Subscriptions", zinovia: "Yes", competitor: "Yes" },
      { feature: "Pay-Per-View Content", zinovia: "Yes", competitor: "Yes" },
      { feature: "Direct Messaging", zinovia: "Built-in", competitor: "Yes" },
      { feature: "Content Encryption", zinovia: "Signed URLs + AES", competitor: "Basic DRM" },
      { feature: "Creator Verification (KYC)", zinovia: "Yes", competitor: "Yes" },
      { feature: "Fan Tips", zinovia: "Yes", competitor: "Yes" },
      { feature: "Analytics Dashboard", zinovia: "Yes", competitor: "Basic" },
      { feature: "Multi-Language Platform", zinovia: "9 languages", competitor: "English only" },
      { feature: "Age Verification", zinovia: "Built-in", competitor: "Yes" },
      { feature: "Mainstream Creator Focus", zinovia: "All niches", competitor: "Adult-focused" },
    ],
    fees: [
      { label: "Platform Fee", zinovia: "Competitive", competitor: "20%" },
      { label: "Payment Processing", zinovia: "Standard processing fee", competitor: "Included" },
      { label: "Monthly Fee", zinovia: "None", competitor: "None" },
      { label: "Payout Fee", zinovia: "None", competitor: "Varies" },
    ],
    payoutSpeed: { zinovia: "48 hours", competitor: "21 days" },
    bestFor: {
      zinovia: "Creators who want better content security, faster payouts, multilingual reach, and a platform that serves all niches equally.",
      competitor: "Adult content creators who want access to OnlyFans' large existing user base.",
    },
    faqs: [
      { q: "Is Zinovia better than OnlyFans?", a: "It depends on your needs. Zinovia offers lower fees, faster payouts (48hr vs 21 days), better content security, and 9-language support. OnlyFans has a larger established user base." },
      { q: "Does Zinovia allow the same content as OnlyFans?", a: "Zinovia supports all content types within our Terms of Service. We serve creators across all niches including fitness, art, music, education, and more." },
      { q: "How much does OnlyFans take vs Zinovia?", a: "OnlyFans takes a flat 20% of creator earnings. Zinovia charges a competitive platform fee that allows creators to keep more of what they earn." },
      { q: "Can I use both Zinovia and OnlyFans?", a: "Yes. Many creators use multiple platforms to diversify their income. You can maintain profiles on both and cross-promote." },
      { q: "Is Zinovia safer than OnlyFans for content?", a: "Zinovia uses signed, time-limited URLs and AES encryption for content delivery, making it significantly harder for content to be leaked or downloaded without authorization." },
    ],
  },
  fanvue: {
    name: "Fanvue",
    slug: "fanvue",
    title: "Zinovia vs Fanvue: Complete Platform Comparison (2026)",
    description: "Compare Zinovia vs Fanvue: features, fees, payout speed, and creator tools. See which platform is right for you.",
    summary: "Both platforms cater to creators, but Zinovia offers faster payouts (48 hours), 9-language support, built-in KYC verification, and secure global payments for international reach.",
    features: [
      { feature: "Monthly Subscriptions", zinovia: "Yes", competitor: "Yes" },
      { feature: "Pay-Per-View Content", zinovia: "Yes", competitor: "Yes" },
      { feature: "Direct Messaging", zinovia: "Built-in", competitor: "Yes" },
      { feature: "Content Encryption", zinovia: "Signed URLs + AES", competitor: "Basic" },
      { feature: "Creator Verification (KYC)", zinovia: "Yes", competitor: "Yes" },
      { feature: "Fan Tips", zinovia: "Yes", competitor: "Yes" },
      { feature: "Analytics Dashboard", zinovia: "Yes", competitor: "Yes" },
      { feature: "Multi-Language Platform", zinovia: "9 languages", competitor: "Limited" },
      { feature: "AI Tools", zinovia: "Planned", competitor: "Yes" },
      { feature: "Referral Program", zinovia: "Planned", competitor: "Yes" },
    ],
    fees: [
      { label: "Platform Fee", zinovia: "Competitive", competitor: "15%" },
      { label: "Payment Processing", zinovia: "Standard processing fee", competitor: "Included" },
      { label: "Monthly Fee", zinovia: "None", competitor: "None" },
      { label: "Payout Fee", zinovia: "None", competitor: "Varies" },
    ],
    payoutSpeed: { zinovia: "48 hours", competitor: "7-14 days" },
    bestFor: {
      zinovia: "Creators who prioritise fast payouts, content security, and multilingual global reach with transparent payment processing.",
      competitor: "Creators interested in AI-powered tools and built-in referral features.",
    },
    faqs: [
      { q: "How does Zinovia compare to Fanvue?", a: "Zinovia offers faster payouts (48hr vs 7-14 days), stronger content encryption (signed URLs + AES), and support for 9 languages. Fanvue offers AI tools and a referral program." },
      { q: "Which has lower fees: Zinovia or Fanvue?", a: "Zinovia charges a competitive platform fee. Fanvue charges 15%. Compare both to see which gives you better take-home earnings for your audience size." },
      { q: "Can I switch from Fanvue to Zinovia?", a: "Yes. Create your Zinovia account, verify your identity, set up your subscription tiers, and start redirecting your audience. The process takes less than 10 minutes." },
      { q: "Does Zinovia have AI features like Fanvue?", a: "AI features are on Zinovia's roadmap. Currently, Zinovia focuses on core monetisation features: subscriptions, paid unlocks, messaging, tips, and secure content delivery." },
      { q: "Which platform is more secure?", a: "Zinovia uses signed, time-limited URLs and AES encryption to protect creator content. This makes it significantly harder for content to be redistributed without permission." },
    ],
  },
  fansly: {
    name: "Fansly",
    slug: "fansly",
    title: "Zinovia vs Fansly: Features, Fees & Creator Tools (2026)",
    description: "Compare Zinovia vs Fansly: subscription features, fees, payout speed, and content security. Make an informed platform choice.",
    summary: "Zinovia differentiates with 48-hour payouts, 9-language multilingual support, secure global payments, and enterprise-grade content encryption.",
    features: [
      { feature: "Monthly Subscriptions", zinovia: "Yes", competitor: "Yes" },
      { feature: "Pay-Per-View Content", zinovia: "Yes", competitor: "Yes" },
      { feature: "Direct Messaging", zinovia: "Built-in", competitor: "Yes" },
      { feature: "Content Encryption", zinovia: "Signed URLs + AES", competitor: "Basic" },
      { feature: "Creator Verification (KYC)", zinovia: "Yes", competitor: "Yes" },
      { feature: "Fan Tips", zinovia: "Yes", competitor: "Yes" },
      { feature: "Analytics Dashboard", zinovia: "Yes", competitor: "Basic" },
      { feature: "Multi-Language Platform", zinovia: "9 languages", competitor: "English only" },
      { feature: "Tiered Subscriptions", zinovia: "Planned", competitor: "Yes" },
      { feature: "Streaming", zinovia: "Planned", competitor: "Yes" },
    ],
    fees: [
      { label: "Platform Fee", zinovia: "Competitive", competitor: "20%" },
      { label: "Payment Processing", zinovia: "Standard processing fee", competitor: "Included" },
      { label: "Monthly Fee", zinovia: "None", competitor: "None" },
      { label: "Payout Fee", zinovia: "None", competitor: "Varies" },
    ],
    payoutSpeed: { zinovia: "48 hours", competitor: "7-14 days" },
    bestFor: {
      zinovia: "Creators who want fast payouts, top-tier content security, multilingual reach, and secure global payments.",
      competitor: "Creators who want tiered subscription models and live streaming built into the platform.",
    },
    faqs: [
      { q: "Is Zinovia better than Fansly?", a: "Both platforms serve creators well. Zinovia excels in payout speed (48 hours), content security (signed URLs + AES), and multilingual support (9 languages). Fansly offers tiered subscriptions and streaming." },
      { q: "What are Fansly's fees compared to Zinovia?", a: "Fansly charges 20% of creator earnings. Zinovia charges a competitive platform fee, allowing creators to retain more of their income." },
      { q: "Can I use Zinovia and Fansly together?", a: "Yes. Many creators maintain profiles on multiple platforms to maximise their reach and diversify income sources." },
      { q: "Does Zinovia support streaming like Fansly?", a: "Live streaming is on Zinovia's roadmap. Currently, Zinovia focuses on subscriptions, paid content, messaging, tips, and secure media delivery." },
      { q: "Which platform handles payouts faster?", a: "Zinovia processes payouts within 48 hours via secure bank transfer. Fansly typically takes 7-14 days for payouts to reach your bank account." },
    ],
  },
  passes: {
    name: "Passes",
    slug: "passes",
    title: "Zinovia vs Passes: Fees, Security & Creator Tools Compared (2026)",
    description: "Compare Zinovia vs Passes: platform fees, anti-leak technology, CRM tools, and payout speed. Find the best creator platform for you.",
    summary: "Zinovia delivers 48-hour payouts, 9-language multilingual reach, and signed-URL content encryption — while Passes offers built-in CRM, anti-screenshot technology, and a 10% platform fee.",
    features: [
      { feature: "Monthly Subscriptions", zinovia: "Yes", competitor: "Yes" },
      { feature: "Pay-Per-View Content", zinovia: "Yes", competitor: "Yes" },
      { feature: "Direct Messaging", zinovia: "Built-in", competitor: "Yes" },
      { feature: "Content Encryption", zinovia: "Signed URLs + AES", competitor: "Anti-screenshot tech" },
      { feature: "Creator Verification (KYC)", zinovia: "Yes", competitor: "Yes" },
      { feature: "Fan Tips", zinovia: "Yes", competitor: "Yes" },
      { feature: "CRM / Fan Management", zinovia: "Basic", competitor: "Built-in CRM" },
      { feature: "Multi-Language Platform", zinovia: "9 languages", competitor: "English primary" },
      { feature: "Age Verification", zinovia: "Built-in", competitor: "Yes" },
      { feature: "Custom Creator Profiles", zinovia: "Yes", competitor: "Yes" },
    ],
    fees: [
      { label: "Platform Fee", zinovia: "Competitive", competitor: "10%" },
      { label: "Payment Processing", zinovia: "Standard processing fee", competitor: "Included" },
      { label: "Monthly Fee", zinovia: "None", competitor: "None" },
      { label: "Payout Fee", zinovia: "None", competitor: "None" },
    ],
    payoutSpeed: { zinovia: "48 hours", competitor: "7 days (weekly)" },
    bestFor: {
      zinovia: "Creators who want the fastest payouts in the industry, enterprise-grade content encryption, and multilingual global reach.",
      competitor: "Creators who want built-in CRM tools, anti-screenshot protection, and fan relationship management in one platform.",
    },
    faqs: [
      { q: "Is Zinovia a good alternative to Passes?", a: "Yes. Zinovia offers faster payouts (48 hours vs weekly), signed-URL content encryption, 9-language support, and built-in KYC and age verification. Passes counters with built-in CRM and anti-screenshot technology." },
      { q: "How do Passes fees compare to Zinovia?", a: "Passes charges a flat 10% platform fee. Zinovia charges a competitive platform fee with no hidden costs or monthly charges. Both platforms include payment processing in their fee structure." },
      { q: "Does Zinovia have anti-screenshot technology like Passes?", a: "Zinovia protects content using signed, time-limited URLs and AES encryption, which prevents unauthorized downloading and sharing. Passes uses client-side anti-screenshot technology to block screen captures." },
      { q: "Which platform pays creators faster: Zinovia or Passes?", a: "Zinovia processes payouts within 48 hours — the fastest in the industry. Passes processes payouts on a weekly schedule, so creators may wait up to 7 days to receive their earnings." },
      { q: "Can I switch from Passes to Zinovia?", a: "Yes. Create your Zinovia account, complete KYC verification, set up your subscription tiers and pricing, then redirect your audience to your new Zinovia profile. The setup process takes under 10 minutes." },
    ],
  },
  loyalfans: {
    name: "LoyalFans",
    slug: "loyalfans",
    title: "Zinovia vs LoyalFans: Creator Platform Comparison (2026)",
    description: "Compare Zinovia vs LoyalFans: fees, payout speed, content security, and features. See which platform helps creators earn more.",
    summary: "Zinovia provides faster payouts (48 hours vs weekly), stronger content encryption, 9-language multilingual support, and competitive fees — while LoyalFans offers an adult-focused platform with an 80/20 revenue split.",
    features: [
      { feature: "Monthly Subscriptions", zinovia: "Yes", competitor: "Yes" },
      { feature: "Pay-Per-View Content", zinovia: "Yes", competitor: "Yes" },
      { feature: "Direct Messaging", zinovia: "Built-in", competitor: "Yes" },
      { feature: "Content Encryption", zinovia: "Signed URLs + AES", competitor: "Basic DRM" },
      { feature: "Creator Verification (KYC)", zinovia: "Yes", competitor: "Yes" },
      { feature: "Fan Tips", zinovia: "Yes", competitor: "Yes" },
      { feature: "Live Streaming", zinovia: "Planned", competitor: "Yes" },
      { feature: "Multi-Language Platform", zinovia: "9 languages", competitor: "English primary" },
      { feature: "Age Verification", zinovia: "Built-in", competitor: "Yes" },
      { feature: "Clip Store / Video Sales", zinovia: "Yes", competitor: "Yes" },
    ],
    fees: [
      { label: "Platform Fee", zinovia: "Competitive", competitor: "20%" },
      { label: "Payment Processing", zinovia: "Standard processing fee", competitor: "Included in 20% fee" },
      { label: "Monthly Fee", zinovia: "None", competitor: "None" },
      { label: "Payout Fee", zinovia: "None", competitor: "Varies by method" },
    ],
    payoutSpeed: { zinovia: "48 hours", competitor: "7 days (weekly)" },
    bestFor: {
      zinovia: "Creators across all niches who want fast payouts, enterprise-grade content security, and the ability to reach a global audience in 9 languages.",
      competitor: "Adult content creators who want live streaming, a clip store, and a dedicated adult-focused audience.",
    },
    faqs: [
      { q: "Is Zinovia better than LoyalFans?", a: "It depends on your priorities. Zinovia offers faster payouts (48 hours vs weekly), stronger content encryption, and 9-language support. LoyalFans offers live streaming, a clip store, and an established adult-focused audience." },
      { q: "How much does LoyalFans take compared to Zinovia?", a: "LoyalFans takes 20% of all creator earnings via their 80/20 revenue split. Zinovia charges a competitive platform fee, helping creators keep more of their income." },
      { q: "Does Zinovia support adult content like LoyalFans?", a: "Zinovia supports creators across all niches within our Terms of Service. LoyalFans is specifically built and marketed as an adult content platform with a dedicated audience in that space." },
      { q: "Which platform has faster payouts: Zinovia or LoyalFans?", a: "Zinovia pays creators within 48 hours, making it the fastest in the industry. LoyalFans processes payouts on a weekly schedule, so earnings can take up to 7 days to reach your account." },
      { q: "Can I migrate from LoyalFans to Zinovia?", a: "Yes. Sign up for Zinovia, complete identity verification, configure your subscription plans, and start directing your fans to your new profile. You can run both platforms simultaneously during the transition." },
    ],
  },
  "ko-fi": {
    name: "Ko-fi",
    slug: "ko-fi",
    title: "Zinovia vs Ko-fi: Features, Fees & Monetisation Compared (2026)",
    description: "Compare Zinovia vs Ko-fi: platform fees, payout speed, content security, and creator tools. Decide which platform fits your creative business.",
    summary: "Zinovia offers enterprise-grade content encryption, 48-hour payouts, built-in KYC and age verification, and subscription-first monetisation — while Ko-fi provides 0% fees on donations, shop functionality, and instant PayPal payouts.",
    features: [
      { feature: "Monthly Subscriptions", zinovia: "Yes", competitor: "Yes (Ko-fi Gold)" },
      { feature: "Pay-Per-View Content", zinovia: "Yes", competitor: "No" },
      { feature: "Direct Messaging", zinovia: "Built-in", competitor: "No" },
      { feature: "Content Encryption", zinovia: "Signed URLs + AES", competitor: "None" },
      { feature: "Creator Verification (KYC)", zinovia: "Yes", competitor: "No" },
      { feature: "One-Time Donations", zinovia: "Via tips", competitor: "Core feature" },
      { feature: "Digital Shop", zinovia: "Paid unlocks", competitor: "Full shop (5% fee)" },
      { feature: "Multi-Language Platform", zinovia: "9 languages", competitor: "English primary" },
      { feature: "Age Verification", zinovia: "Built-in", competitor: "No" },
      { feature: "Commission Marketplace", zinovia: "No", competitor: "Yes" },
    ],
    fees: [
      { label: "Platform Fee", zinovia: "Competitive", competitor: "0% on donations, 5% on shop" },
      { label: "Payment Processing", zinovia: "Standard processing fee", competitor: "PayPal / Stripe fees apply" },
      { label: "Monthly Fee", zinovia: "None", competitor: "$6/mo for Ko-fi Gold" },
      { label: "Payout Fee", zinovia: "None", competitor: "PayPal / Stripe fees" },
    ],
    payoutSpeed: { zinovia: "48 hours", competitor: "Instant (via PayPal)" },
    bestFor: {
      zinovia: "Creators who want subscription-based monetisation, secure private content delivery, fast payouts, and multilingual global reach.",
      competitor: "SFW creators who want zero-fee donations, a simple digital shop, and instant PayPal payouts with minimal setup.",
    },
    faqs: [
      { q: "How does Zinovia compare to Ko-fi?", a: "Zinovia is a subscription-first platform with content encryption, direct messaging, KYC verification, and 48-hour payouts. Ko-fi is a tip-jar and shop platform with 0% fees on donations, instant PayPal payouts, and a commission marketplace." },
      { q: "Is Ko-fi really free to use?", a: "Ko-fi charges 0% on donations and tips. However, their digital shop takes 5%, and advanced features like memberships require Ko-fi Gold at $6/month. PayPal and Stripe processing fees still apply on all transactions." },
      { q: "Does Zinovia support one-time payments like Ko-fi?", a: "Yes. Zinovia supports fan tips and paid content unlocks for one-time payments, in addition to recurring subscriptions. Ko-fi specialises in one-time donations and also offers memberships via Ko-fi Gold." },
      { q: "Which platform is more secure for content creators?", a: "Zinovia uses signed, time-limited URLs and AES encryption to protect all content from unauthorized access. Ko-fi does not offer content encryption or DRM, as it focuses primarily on SFW donations and digital product sales." },
      { q: "Should I use Zinovia or Ko-fi for memberships?", a: "If you need private content delivery, content encryption, direct messaging, and fast bank payouts, choose Zinovia. If you want a simple, low-cost membership page with PayPal payouts and a built-in shop, Ko-fi Gold is a solid choice." },
    ],
  },
  gumroad: {
    name: "Gumroad",
    slug: "gumroad",
    title: "Zinovia vs Gumroad: Creator Monetisation Comparison (2026)",
    description: "Compare Zinovia vs Gumroad: platform fees, features, payout speed, and content delivery. Choose the right platform for your creator business.",
    summary: "Zinovia focuses on recurring subscriptions with encrypted content delivery, 48-hour payouts, and built-in messaging — while Gumroad excels at one-time digital product sales with a 10% flat fee and instant payouts.",
    features: [
      { feature: "Monthly Subscriptions", zinovia: "Yes", competitor: "Yes (Memberships)" },
      { feature: "Pay-Per-View Content", zinovia: "Yes", competitor: "One-time purchases" },
      { feature: "Direct Messaging", zinovia: "Built-in", competitor: "No" },
      { feature: "Content Encryption", zinovia: "Signed URLs + AES", competitor: "Basic link protection" },
      { feature: "Creator Verification (KYC)", zinovia: "Yes", competitor: "No" },
      { feature: "Digital Product Sales", zinovia: "Via paid unlocks", competitor: "Core feature" },
      { feature: "Email Marketing", zinovia: "No", competitor: "Built-in (Workflows)" },
      { feature: "Multi-Language Platform", zinovia: "9 languages", competitor: "English primary" },
      { feature: "Age Verification", zinovia: "Built-in", competitor: "No" },
      { feature: "Affiliate Program Tools", zinovia: "Planned", competitor: "Yes (Gumroad Discover)" },
    ],
    fees: [
      { label: "Platform Fee", zinovia: "Competitive", competitor: "10% flat fee" },
      { label: "Payment Processing", zinovia: "Standard processing fee", competitor: "Included in 10%" },
      { label: "Monthly Fee", zinovia: "None", competitor: "None" },
      { label: "Payout Fee", zinovia: "None", competitor: "None (via Stripe)" },
    ],
    payoutSpeed: { zinovia: "48 hours", competitor: "Instant (via Stripe Connect)" },
    bestFor: {
      zinovia: "Creators who want recurring subscription income, private encrypted content, direct fan messaging, and 9-language multilingual support.",
      competitor: "Digital product sellers (ebooks, courses, templates) who want a simple storefront with built-in email marketing and affiliate tools.",
    },
    faqs: [
      { q: "Is Zinovia a good alternative to Gumroad?", a: "It depends on your business model. Zinovia excels at subscription-based monetisation with encrypted content delivery and direct messaging. Gumroad is better for one-time digital product sales with built-in email marketing." },
      { q: "How do Gumroad's fees compare to Zinovia?", a: "Gumroad charges a flat 10% on every transaction. Zinovia charges a competitive platform fee. Neither platform charges monthly subscription fees to creators." },
      { q: "Does Zinovia support digital product sales like Gumroad?", a: "Zinovia supports paid content unlocks for selling individual pieces of content. However, Gumroad offers a full e-commerce storefront with product pages, discount codes, and license key delivery." },
      { q: "Which platform has better content protection?", a: "Zinovia uses signed, time-limited URLs and AES encryption for all content. Gumroad offers basic link protection and PDF stamping, but content files can generally be downloaded and shared more easily." },
      { q: "Can I sell subscriptions on both Zinovia and Gumroad?", a: "Yes. Zinovia's subscription system is built for private content delivery with messaging and encryption. Gumroad offers memberships but is primarily designed for one-time product sales rather than ongoing exclusive content." },
    ],
  },
  fanfix: {
    name: "Fanfix",
    slug: "fanfix",
    title: "Zinovia vs Fanfix: SFW Creator Platforms Compared (2026)",
    description: "Compare Zinovia vs Fanfix: fees, features, content policies, and payouts. See which platform is right for your clean content business.",
    summary: "Zinovia supports creators across all niches with 48-hour payouts, content encryption, and 9-language support — while Fanfix is a SFW-only platform targeting Gen Z creators, now owned by SuperOrdinary.",
    features: [
      { feature: "Monthly Subscriptions", zinovia: "Yes", competitor: "Yes" },
      { feature: "Pay-Per-View Content", zinovia: "Yes", competitor: "Yes" },
      { feature: "Direct Messaging", zinovia: "Built-in", competitor: "Yes" },
      { feature: "Content Encryption", zinovia: "Signed URLs + AES", competitor: "Basic" },
      { feature: "Creator Verification (KYC)", zinovia: "Yes", competitor: "Application-based" },
      { feature: "Fan Tips", zinovia: "Yes", competitor: "Yes" },
      { feature: "NSFW Content Allowed", zinovia: "Per ToS", competitor: "No (SFW only)" },
      { feature: "Multi-Language Platform", zinovia: "9 languages", competitor: "English only" },
      { feature: "Age Verification", zinovia: "Built-in", competitor: "Basic" },
      { feature: "Open Creator Signup", zinovia: "Yes", competitor: "Application / invite only" },
    ],
    fees: [
      { label: "Platform Fee", zinovia: "Competitive", competitor: "20%" },
      { label: "Payment Processing", zinovia: "Standard processing fee", competitor: "Included in 20%" },
      { label: "Monthly Fee", zinovia: "None", competitor: "None" },
      { label: "Payout Fee", zinovia: "None", competitor: "Varies" },
    ],
    payoutSpeed: { zinovia: "48 hours", competitor: "14-30 days" },
    bestFor: {
      zinovia: "Creators across all niches who want fast payouts, open signup, enterprise-grade encryption, and multilingual global reach.",
      competitor: "SFW Gen Z creators and influencers who want a clean-content-only platform with brand-safe positioning.",
    },
    faqs: [
      { q: "How does Zinovia compare to Fanfix?", a: "Zinovia is an open platform for all creators with 48-hour payouts, content encryption, and 9-language support. Fanfix is SFW-only, invite-based, targets Gen Z creators, and was acquired by SuperOrdinary. Fanfix takes 20% vs Zinovia's competitive fee." },
      { q: "Is Fanfix only for clean content?", a: "Yes. Fanfix strictly prohibits NSFW content and positions itself as a brand-safe platform for Gen Z creators and influencers. Zinovia supports creators across all niches within its Terms of Service." },
      { q: "Can anyone join Fanfix vs Zinovia?", a: "Zinovia offers open signup — any creator can join and start monetising. Fanfix uses an application or invite-only system, meaning not all creators are accepted. This can limit access for newer or smaller creators." },
      { q: "Which platform pays creators faster: Zinovia or Fanfix?", a: "Zinovia pays within 48 hours, the fastest in the industry. Fanfix typically processes payouts over 14-30 days, which means creators wait significantly longer to access their earnings." },
      { q: "What happened to Fanfix?", a: "Fanfix was acquired by SuperOrdinary, a creator commerce company. The platform continues to operate as a SFW creator subscription service, but its long-term roadmap is now tied to SuperOrdinary's broader strategy." },
    ],
  },
  unfiltrd: {
    name: "Unfiltrd",
    slug: "unfiltrd",
    title: "Zinovia vs Unfiltrd: Creator Platform Showdown (2026)",
    description: "Compare Zinovia vs Unfiltrd: fees, features, content security, and payout speed. Find out which creator platform gives you more.",
    summary: "Zinovia offers 48-hour payouts, signed-URL content encryption, and 9-language multilingual support — while Unfiltrd is a newer platform with subscription and tipping features at a 20% platform fee.",
    features: [
      { feature: "Monthly Subscriptions", zinovia: "Yes", competitor: "Yes" },
      { feature: "Pay-Per-View Content", zinovia: "Yes", competitor: "Yes" },
      { feature: "Direct Messaging", zinovia: "Built-in", competitor: "Yes" },
      { feature: "Content Encryption", zinovia: "Signed URLs + AES", competitor: "Basic" },
      { feature: "Creator Verification (KYC)", zinovia: "Yes", competitor: "Yes" },
      { feature: "Fan Tips", zinovia: "Yes", competitor: "Yes" },
      { feature: "Analytics Dashboard", zinovia: "Yes", competitor: "Basic" },
      { feature: "Multi-Language Platform", zinovia: "9 languages", competitor: "English only" },
      { feature: "Age Verification", zinovia: "Built-in", competitor: "Yes" },
      { feature: "Established Platform History", zinovia: "Yes", competitor: "Newer platform" },
    ],
    fees: [
      { label: "Platform Fee", zinovia: "Competitive", competitor: "20%" },
      { label: "Payment Processing", zinovia: "Standard processing fee", competitor: "Included in 20%" },
      { label: "Monthly Fee", zinovia: "None", competitor: "None" },
      { label: "Payout Fee", zinovia: "None", competitor: "Varies" },
    ],
    payoutSpeed: { zinovia: "48 hours", competitor: "7-14 days" },
    bestFor: {
      zinovia: "Creators who want fast payouts, enterprise-grade content security, multilingual support, and a reliable platform with no monthly fees.",
      competitor: "Creators looking for a newer platform alternative with subscription and tipping features.",
    },
    faqs: [
      { q: "Is Zinovia better than Unfiltrd?", a: "Zinovia offers faster payouts (48 hours vs 7-14 days), stronger content encryption (signed URLs + AES), and 9-language multilingual support. Unfiltrd is a newer entrant that offers subscriptions and tips at a 20% platform fee." },
      { q: "How much does Unfiltrd charge compared to Zinovia?", a: "Unfiltrd takes 20% of creator earnings. Zinovia charges a competitive platform fee with no hidden costs, no monthly charges, and no payout fees." },
      { q: "Is Unfiltrd a reliable platform?", a: "Unfiltrd is a newer platform in the creator economy space. While it offers standard monetisation features, it has a shorter track record than more established platforms. Zinovia provides built-in KYC verification and enterprise-grade security." },
      { q: "Which platform has better content protection?", a: "Zinovia uses signed, time-limited URLs and AES encryption to protect creator content from leaks and unauthorized access. Unfiltrd offers basic content protection but does not match Zinovia's enterprise-grade encryption approach." },
      { q: "Can I switch from Unfiltrd to Zinovia?", a: "Yes. Sign up on Zinovia, verify your identity, set up your subscription tiers, and redirect your fans. You can maintain profiles on both platforms during the transition to avoid losing subscribers." },
    ],
  },
  mym: {
    name: "MYM / MYM.fans",
    slug: "mym",
    title: "Zinovia vs MYM.fans: Fees, Payouts & Features Compared (2026)",
    description: "Compare Zinovia vs MYM (MYM.fans): platform fees, payout speed, content security, and multilingual support. See which platform is best for creators.",
    summary: "Zinovia offers 48-hour payouts, competitive fees, and 9-language support — while MYM.fans is a Europe-based platform taking 25% of creator earnings with monthly payout cycles.",
    features: [
      { feature: "Monthly Subscriptions", zinovia: "Yes", competitor: "Yes" },
      { feature: "Pay-Per-View Content", zinovia: "Yes", competitor: "Yes (Private Media)" },
      { feature: "Direct Messaging", zinovia: "Built-in", competitor: "Yes (Push Messages)" },
      { feature: "Content Encryption", zinovia: "Signed URLs + AES", competitor: "Basic" },
      { feature: "Creator Verification (KYC)", zinovia: "Yes", competitor: "Yes" },
      { feature: "Fan Tips", zinovia: "Yes", competitor: "Yes" },
      { feature: "Content Requests", zinovia: "Via messaging", competitor: "Built-in feature" },
      { feature: "Multi-Language Platform", zinovia: "9 languages", competitor: "French / English" },
      { feature: "Age Verification", zinovia: "Built-in", competitor: "Yes" },
      { feature: "European Payment Support", zinovia: "Global payments", competitor: "Europe-focused" },
    ],
    fees: [
      { label: "Platform Fee", zinovia: "Competitive", competitor: "25%" },
      { label: "Payment Processing", zinovia: "Standard processing fee", competitor: "Included in 25%" },
      { label: "Monthly Fee", zinovia: "None", competitor: "None" },
      { label: "Payout Fee", zinovia: "None", competitor: "Varies by method" },
    ],
    payoutSpeed: { zinovia: "48 hours", competitor: "Monthly" },
    bestFor: {
      zinovia: "Creators worldwide who want fast payouts, competitive fees, enterprise-grade content encryption, and 9-language multilingual reach.",
      competitor: "European creators, particularly French-speaking, who want built-in content request features and a Europe-based platform.",
    },
    faqs: [
      { q: "How does Zinovia compare to MYM.fans?", a: "Zinovia offers 48-hour payouts (vs monthly), competitive fees (vs 25%), signed-URL content encryption, and 9-language support. MYM.fans is Europe-based with built-in content request features and a French-English platform." },
      { q: "How much does MYM take from creators?", a: "MYM.fans takes 25% of all creator earnings — one of the highest rates in the industry. Zinovia charges a competitive platform fee, letting creators keep significantly more of their income." },
      { q: "Is MYM.fans only for European creators?", a: "MYM.fans is based in France and primarily serves European creators, with the platform available in French and English. Zinovia serves creators globally with support for 9 languages and secure international payments." },
      { q: "Which platform pays creators faster: Zinovia or MYM?", a: "Zinovia pays within 48 hours — the fastest in the creator platform industry. MYM.fans processes payouts on a monthly cycle, meaning creators can wait up to 30+ days to receive their earnings." },
      { q: "Can I use Zinovia instead of MYM.fans?", a: "Yes. Zinovia is available globally and supports European creators with secure international payments, 9-language support, and faster payouts. Sign up, verify your identity, and set up your profile in minutes." },
    ],
  },
  "scrile-connect": {
    name: "Scrile Connect",
    slug: "scrile-connect",
    title: "Zinovia vs Scrile Connect: Hosted vs White-Label Compared (2026)",
    description: "Compare Zinovia vs Scrile Connect: managed platform vs white-label solution. Understand fees, setup effort, and features for creator businesses.",
    summary: "Zinovia is a fully managed platform with 48-hour payouts, content encryption, and zero setup costs — while Scrile Connect is a white-label solution requiring a one-time license purchase where creators build and manage their own platform.",
    features: [
      { feature: "Monthly Subscriptions", zinovia: "Yes", competitor: "Yes (self-hosted)" },
      { feature: "Pay-Per-View Content", zinovia: "Yes", competitor: "Yes (self-hosted)" },
      { feature: "Direct Messaging", zinovia: "Built-in", competitor: "Yes (self-hosted)" },
      { feature: "Content Encryption", zinovia: "Signed URLs + AES", competitor: "Depends on setup" },
      { feature: "Creator Verification (KYC)", zinovia: "Yes", competitor: "Self-managed" },
      { feature: "Fully Managed Platform", zinovia: "Yes", competitor: "No (white-label)" },
      { feature: "No Technical Setup Required", zinovia: "Yes", competitor: "No (requires development)" },
      { feature: "Multi-Language Platform", zinovia: "9 languages", competitor: "Customisable" },
      { feature: "Age Verification", zinovia: "Built-in", competitor: "Self-managed" },
      { feature: "Custom Branding", zinovia: "Creator profiles", competitor: "Full white-label" },
    ],
    fees: [
      { label: "Platform Fee", zinovia: "Competitive", competitor: "0% (you keep all revenue)" },
      { label: "Payment Processing", zinovia: "Standard processing fee", competitor: "Your own merchant account" },
      { label: "Monthly Fee", zinovia: "None", competitor: "Hosting + maintenance costs" },
      { label: "Upfront Cost", zinovia: "None", competitor: "One-time license fee" },
    ],
    payoutSpeed: { zinovia: "48 hours", competitor: "Self-managed (depends on payment provider)" },
    bestFor: {
      zinovia: "Individual creators and small teams who want a ready-to-use platform with fast payouts, built-in security, and zero technical overhead.",
      competitor: "Established creator businesses or agencies that want full brand ownership, 100% revenue retention, and have the technical resources to run their own platform.",
    },
    faqs: [
      { q: "What is the difference between Zinovia and Scrile Connect?", a: "Zinovia is a fully managed platform — sign up and start earning in minutes. Scrile Connect is a white-label solution: you purchase a license and build your own creator platform. Zinovia handles hosting, payments, security, and support; Scrile Connect gives you full control but requires technical resources." },
      { q: "Does Scrile Connect really take 0% of earnings?", a: "Scrile Connect charges no ongoing revenue share. However, you pay a one-time license fee plus ongoing hosting, maintenance, and payment processing costs through your own merchant account. Total costs can exceed platform fees depending on volume." },
      { q: "Do I need technical skills for Scrile Connect?", a: "Yes. Scrile Connect requires server setup, payment gateway integration, and ongoing platform maintenance. Zinovia requires zero technical skills — create an account, verify your identity, and start monetising immediately." },
      { q: "Which is cheaper: Zinovia or Scrile Connect?", a: "For most individual creators, Zinovia is more cost-effective because there are no upfront costs, no hosting fees, and no maintenance overhead. Scrile Connect may be cheaper at very high revenue volumes where the 0% commission offsets the license and infrastructure costs." },
      { q: "Can I migrate from Scrile Connect to Zinovia?", a: "Yes. If managing your own platform becomes too complex or costly, you can redirect your audience to a Zinovia profile. You will benefit from managed infrastructure, 48-hour payouts, and built-in content encryption without any technical maintenance." },
    ],
  },
  fourthwall: {
    name: "Fourthwall",
    slug: "fourthwall",
    title: "Zinovia vs Fourthwall: Creator Monetisation Platforms Compared (2026)",
    description: "Compare Zinovia vs Fourthwall: memberships, content security, payout speed, and creator tools. Find the best platform for your audience.",
    summary: "Zinovia specialises in subscription content with encrypted delivery, 48-hour payouts, and direct messaging — while Fourthwall combines 0%-fee memberships with merchandise sales and is built primarily for YouTubers and streamers.",
    features: [
      { feature: "Monthly Subscriptions", zinovia: "Yes", competitor: "Yes (0% fee on memberships)" },
      { feature: "Pay-Per-View Content", zinovia: "Yes", competitor: "Digital product sales" },
      { feature: "Direct Messaging", zinovia: "Built-in", competitor: "No" },
      { feature: "Content Encryption", zinovia: "Signed URLs + AES", competitor: "None" },
      { feature: "Creator Verification (KYC)", zinovia: "Yes", competitor: "No" },
      { feature: "Merch / Physical Products", zinovia: "No", competitor: "Yes (core feature)" },
      { feature: "Custom Storefront", zinovia: "Creator profiles", competitor: "Full custom website" },
      { feature: "Multi-Language Platform", zinovia: "9 languages", competitor: "English primary" },
      { feature: "Age Verification", zinovia: "Built-in", competitor: "No" },
      { feature: "YouTube / Twitch Integration", zinovia: "No", competitor: "Yes (member-only perks)" },
    ],
    fees: [
      { label: "Platform Fee", zinovia: "Competitive", competitor: "0% on memberships" },
      { label: "Merch / Product Fee", zinovia: "N/A", competitor: "Margin on merch production" },
      { label: "Monthly Fee", zinovia: "None", competitor: "None" },
      { label: "Payout Fee", zinovia: "None", competitor: "Varies by method" },
    ],
    payoutSpeed: { zinovia: "48 hours", competitor: "14-30 days" },
    bestFor: {
      zinovia: "Creators who want private subscription content with encrypted delivery, fast 48-hour payouts, direct fan messaging, and multilingual global reach.",
      competitor: "YouTubers and streamers who want to sell branded merchandise alongside memberships with YouTube and Twitch integration.",
    },
    faqs: [
      { q: "How does Zinovia compare to Fourthwall?", a: "Zinovia focuses on subscription content with encrypted delivery, direct messaging, and 48-hour payouts. Fourthwall combines 0%-fee memberships with merchandise sales and is built for YouTubers and streamers who want custom storefronts with merch integration." },
      { q: "Does Fourthwall really charge 0% on memberships?", a: "Yes. Fourthwall charges 0% platform fee on membership revenue. However, they earn revenue through margins on merchandise production and fulfillment. Payment processing fees still apply to all transactions." },
      { q: "Can I sell merchandise on Zinovia like Fourthwall?", a: "Zinovia focuses on digital content monetisation — subscriptions, paid unlocks, tips, and messaging. Fourthwall is purpose-built for merchandise with print-on-demand, inventory management, and custom storefronts. If merch is core to your business, Fourthwall may complement Zinovia." },
      { q: "Which platform pays faster: Zinovia or Fourthwall?", a: "Zinovia processes payouts within 48 hours — the fastest in the creator platform industry. Fourthwall typically takes 14-30 days for payouts, and merch earnings depend on production and shipping timelines." },
      { q: "Should I use Zinovia or Fourthwall as a YouTuber?", a: "If you want private subscription content with encrypted delivery and fast payouts, choose Zinovia. If you want to sell branded merchandise alongside memberships with YouTube integration and member-only perks, Fourthwall is designed specifically for that use case. Many creators use both." },
    ],
  },
};

export function getComparison(slug: string): ComparisonData | undefined {
  return COMPARISONS[slug];
}

export function getAllComparisonSlugs(): string[] {
  return Object.keys(COMPARISONS);
}
