from __future__ import annotations

POST_TYPE_TEXT = "TEXT"
POST_TYPE_IMAGE = "IMAGE"
POST_TYPE_VIDEO = "VIDEO"

VISIBILITY_PUBLIC = "PUBLIC"
VISIBILITY_FOLLOWERS = "FOLLOWERS"
VISIBILITY_SUBSCRIBERS = "SUBSCRIBERS"

POST_STATUS_DRAFT = "DRAFT"
POST_STATUS_SCHEDULED = "SCHEDULED"
POST_STATUS_PUBLISHED = "PUBLISHED"

DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100
